### PR TITLE
Add UI Prototype link to readme

### PR DESCRIPTION
**Pull request by LunlunChin**

### CODE REVIEW

**Comment by guyluz11** [comment]
You have forgotten to change the link of the text to the figma link

**Comment by LunlunChin** [comment]
Sorry for the mistake, I have changed it to the right link, please check again, thanks

**Comment by guyluz11** [comment]
Thanks for the pr @LunlunChin that looks awesome.

About the app design we should sit and discuss it because I want the flow to stay mostly the same but the design of it can change.

And a happy Hacktoberfest :D

**Comment by LunlunChin** [comment]
Sure, lets schedule a time to discuss about this, thanks!

**Pull request merged**
