### PR TITLE
Added Url functionality in navigation (#103)

### PR DESCRIPTION
**Pull request by ismailyegnr**
Fix: Navigating between pages should change URL #103

### CODE REVIEW

**Comment by guyluz11** [comment]
Wow it works, and with small changes that's cool, was it added in one of the last updates?

Thanks for the pr @ismailyegnr and a happy Hacktoberfest

**Comment by ismailyegnr** [comment]
It looks like this solution has been around for a while. You can examine an example here https://github.com/flutter/flutter/issues/53361#issuecomment-607521191

Thank you @guyluz11

**Comment by guyluz11** [comment]
One more flutter (website) question for you as it seems you know some staff.

Is there a way/package to make a scroll behave like in the big tec sites?
Where scrolling down takes you to the next section and you can't stop scrolling in between sections

Example:
https://webdevtrick.com/demos/full-page-scrolling/#secondSection
or
https://alvarotrigo.com/fullPage/#page2

**Comment by ismailyegnr** [comment]
Actually Flutter already provides a way around for this with PageView widget.

I made a small example for this. You can try it and customize it according to your requests. 

Thanks

```dart
class HomePage extends StatefulWidget {
  const HomePage({super.key});

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage>
    with SingleTickerProviderStateMixin {
  late final TabController indicatorController;

  final PageController pageController = PageController();

  int currentPage = 0;

  @override
  void initState() {
    super.initState();

    indicatorController = TabController(length: 3, vsync: this);

    pageController.addListener(() {
      if (pageController.page?.round() != currentPage) {
        currentPage = pageController.page!.round();
        indicatorController.index = currentPage;
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        PageView(
          controller: pageController,
          scrollDirection: Axis.vertical,
          children: [
            Container(
              color: Colors.amber,
              child: const Center(
                child: Text('First Page'),
              ),
            ),
            Container(
              color: Colors.blue,
              child: const Center(
                child: Text('Second Page'),
              ),
            ),
            Container(
              color: Colors.red,
              child: const Center(
                child: Text('Third Page'),
              ),
            ),
          ],
        ),
        Align(
          alignment: Alignment.centerRight,
          child: RotatedBox(
            quarterTurns: 1,
            child: TabPageSelector(
              controller: indicatorController,
              indicatorSize: 12,
              selectedColor: Colors.black,
            ),
          ),
        ),
      ],
    );
  }
}
```

**Comment by guyluz11** [comment]
Man you know your stuff XD

In this example it required scrolling a lot in order to change one section so this is something that needs to be addressed, but this is definitely a start.

**Comment by guyluz11** [comment]
I have created a complicated way to fix this using bloc.

Here is a link to the UI folder of it
https://github.com/guyluz11/CBJ_Site/tree/dev/lib/presentation/new_home_page
And the bloc part
https://github.com/guyluz11/CBJ_Site/tree/dev/lib/application/new_home_page

**Pull request merged**
