### PR TITLE
New UI for desktop landing pages

### PR DESCRIPTION
**Pull request by LunlunChin**
Issue : https://github.com/CyBear-Jinni/CBJ_Site/issues/100

Prototype link:
https://www.figma.com/proto/MhxmWzNxRX2KR17uwsYehf/Bear?node-id=1%3A2&scaling=min-zoom&page-id=0%3A1

Feel free to give any feedback for improvement of this UI

### CODE REVIEW

**Comment by guyluz11** [comment]
Hi @LunlunChin 
First of all awesome job with the UI
It looks professional.

Here are some thoughts that we need to address.

1. The page looks too dim, it makes them feel that this site helps you go to sleep even though it looks professional.
2. The logo of the panda at the top should be CyBear Jinni log which is higher, do you think that it will fit and look good?.
we can draw inspiration from the logo to the vibe of the site whenever we create it. 
3. Liked the art on the background, it makes it look modern and with consistent design in mind as the same form of art appears on the multiple background images.
4. I guess that you didn't add the links to all the platforms at the bottom but it will work with the design. Tell me what you think.
5. The Supported vendors suppose to be gray? or are just missing the files?
6. How to set up is to black and feels empty as the text is flowing around.

**Comment by LunlunChin** [comment]
Hi @guyluz11
Thanks for your feedback

This design was more focuses on darker theme, so as you can see the background is dark in color.

The vendor color has been changed to grey to make it fit to the dark theme

I will try to make a bright and light theme tomorrow and see if it looks better in a way, thanks 👌👌

**Comment by LunlunChin** [comment]
Hi @guyluz11

I have edited the design to a lighter theme
Feel free to test them out here:
https://www.figma.com/proto/MhxmWzNxRX2KR17uwsYehf/Bear?node-id=27%3A2&scaling=min-zoom&page-id=0%3A1

Looking forward to your feedback!

**Comment by guyluz11** [comment]
Much better, are you sure that we can use the images on our site?

Here is a link to our logo

https://github.com/CyBear-Jinni/CBJ_Site/blob/master/assets/images/cbj_app_icon_no_bg.png

https://github.com/CyBear-Jinni/CBJ_Site/blob/master/assets/images/cbj_logo_no_background.png

It needs a little bit more polishing but we are in a good direction.

By the way I thought about it and adding moc images to the project will not be god as they are heavy.

So in the pr add a link to the moc on sigma in the readme.

Make sure to remove the previously uploaded images from the git history.

**Comment by LunlunChin** [comment]
Alright, I have done removing all the images and added a link to the readme section,

I have idea which is to use the long height logo when its on the top and make it into the "only head logo" when user scroll down.
for this, we might need to make the navbar on fixed position

**Comment by guyluz11** [comment]
You have removed the images, but it still exist in the history of the commits

Screenshot_20221009-102808_Firefox


You need to create a fork from the main repo from scratch.
This weight will not contain the previous history that you have committed.

**Pull request closed without merging**
