### PR TITLE
Fix bottom border issue on Mobile 

### PR DESCRIPTION
**Pull request by Aaliya-Ali**
Fixes the bottom border on the Mobile view of the Integrations Screen. Solves #60 

image

### What I did:
Gave a horizontal margin of 20 to the container containing the listview to match ```BottomNavigationMenuMobileTablet``` Widget's padding.

### CODE REVIEW

**Comment by Aaliya-Ali** [comment]
Done

**Comment by guyluz11** [comment]
Nice one :) 
Happy Hacktoberfest @Aaliya-Ali 

I have several easy issues in the other repos here, tell me if you want me to suggest one for you.

**Comment by Aaliya-Ali** [comment]
Sure I'd be happy to help :)

**Comment by guyluz11** [comment]
Cool, so I am linking one that is a little bit harder
https://github.com/CyBear-Jinni/cbj_app/issues/318

Feel free to ask for help in the discord server or in the issues.

**Pull request merged**
